setup comprehensive ci/cd pipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,75 +1,75 @@
-name: CI/CD Pipeline for Dockerized Application
+# name: CI/CD Pipeline for Dockerized Application
 
-on:
-  push:
-    branches:
-      - dev
+# on:
+#   push:
+#     branches:
+#       - dev
 
-env:
-  IMAGE_NAME: imranwebstudio/alvaro-server:latest
+# env:
+#   IMAGE_NAME: imranwebstudio/alvaro-server:latest
 
-jobs:
-  build-and-push:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+# jobs:
+#   build-and-push:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v4
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+#       - name: Set up Docker Buildx
+#         uses: docker/setup-buildx-action@v3
 
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+#       - name: Log in to Docker Hub
+#         uses: docker/login-action@v3
+#         with:
+#           username: ${{ secrets.DOCKER_USERNAME }}
+#           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Build Docker image
-        run: |
-          docker compose build --no-cache && docker compose push
+#       - name: Build Docker image
+#         run: |
+#           docker compose build --no-cache && docker compose push
 
-  deploy:
-    name: Deploy to VPS
-    runs-on: ubuntu-latest
-    needs: build-and-push
+#   deploy:
+#     name: Deploy to VPS
+#     runs-on: ubuntu-latest
+#     needs: build-and-push
 
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@v4
+#     steps:
+#       - name: Checkout repo
+#         uses: actions/checkout@v4
 
-      - name: SSH into VPS and deploy
-        uses: appleboy/ssh-action@v0.1.6
-        with:
-          host: ${{ secrets.VPS_HOST }}
-          username: root
-          password: ${{ secrets.VPS_PASSWORD }}
-          script: |
+#       - name: SSH into VPS and deploy
+#         uses: appleboy/ssh-action@v0.1.6
+#         with:
+#           host: ${{ secrets.VPS_HOST }}
+#           username: root
+#           password: ${{ secrets.VPS_PASSWORD }}
+#           script: |
 
-            ls -a
-            cd ~/alvaro-server
-            ls -a
+#             ls -a
+#             cd ~/alvaro-server
+#             ls -a
 
-            echo "Stopping and removing old containers..."
-            docker compose down --remove-orphans
+#             echo "Stopping and removing old containers..."
+#             docker compose down --remove-orphans
 
-            echo "Removing old images..."
-            docker compose rm -f
+#             echo "Removing old images..."
+#             docker compose rm -f
 
-            echo "Pulling latest images..."
-            docker compose pull
+#             echo "Pulling latest images..."
+#             docker compose pull
 
-            echo "Starting new containers..."
-            docker compose prod up -d
+#             echo "Starting new containers..."
+#             docker compose prod up -d
 
-            echo "Waiting for containers remove unused images"
-            docker image prune -f
+#             echo "Waiting for containers remove unused images"
+#             docker image prune -f
 
-            echo "Deployment completed successfully. :)"
+#             echo "Deployment completed successfully. :)"
 
-      - name: Verify Docker Compose status
-        run: |
-          if docker-compose ps | grep -q "Exit"; then
-            echo "Error: Docker containers are not running properly.";
-            docker-compose logs
-            exit 1;
-          fi
+#       - name: Verify Docker Compose status
+#         run: |
+#           if docker-compose ps | grep -q "Exit"; then
+#             echo "Error: Docker containers are not running properly.";
+#             docker-compose logs
+#             exit 1;
+#           fi
